---
title: "BudeMapPresentation"
author: "Kerin Grewal"
date: "April 1, 2018"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include = FALSE, echo= FALSE}
#library(ggmap)
library(tidyverse)
library(magick)


knitr::opts_chunk$set(echo = FALSE)

map1 <- get_map(location = "Bude", zoom = 14)

watermap <- get_map(location = "Bude", maptype = "watercolor", zoom = 14)

df <- data.frame(location = c('Crooklets Beach', 'Summerleaze Beach', 'The Barrel at Bude'), stringsAsFactors = FALSE)

geo_loc <- geocode(df$location)

df1 <- cbind(df, geo_loc)


start <- "Bude North Cornwall Cricket Club"
end <- "The Barrel at Bude"
path <- route(start, end, structure = "route")

cricket_club <- image_scale(image_read("https://i.pinimg.com/564x/42/21/20/42212062d2dbf181dc1b1eaa160dce53.jpg"))

summ_beach <- image_scale(image_read("https://www.natureflip.com/sites/default/files/photo//bude-summerleaze-beach-summerleaze-beach-at-bude-cornwall.jpg"))

crook_beach <- image_scale(image_read("https://www.thebeachguide.co.uk/public/geophotos/1450635.jpg"))

```


##Roadmap of Bude
```{r, echo = FALSE}

gc_Hotel1 <- geocode("17-18 Summerleaze Crescent, Bude EX23 8HJ, England")
data_Hotel1 <- as.data.frame(gc_Hotel1)
map_Hotel1 <- get_map(data_Hotel1, zoom=15)
#Hotel1_RoadMap <- ggmap(map_Hotel1) + 
#  geom_point(aes(x = lon, y = lat), data = data_Hotel1, color = "purple", size = 3) +
#  geom_text(aes(x = lon, y = lat, label=" Atlantic House Hotel "), data = data_Hotel1, vjust=1.5,size=3)
#Hotel1_RoadMap


gc_Hotel2 <- geocode("Downs View, Bude EX23 8RE, England")
data_Hotel2 <- as.data.frame(gc_Hotel2)
map_Hotel2 <- get_map(data_Hotel2, zoom=15)

# Hotel2_RoadMap <- ggmap(map_Hotel2) + 
#   geom_point(aes(x = lon, y = lat), data = data_Hotel2, color = "orange", size = 3) +
#   geom_text(aes(x = lon, y = lat, label="Hebasca Hotel"), data = data_Hotel2, vjust=1.5,size=3)
# Hotel2_RoadMap

ggmap(map1) + 
  geom_point(data = df1, aes(x = lon, y = lat), color = 'red') + 
  geom_path(
    aes(x = lon, y = lat), color = "blue", size = 1.5,
    data = path, lineend = "round")+
  geom_point(aes(x = lon, y = lat), data = data_Hotel1, color = "purple", size = 3) +
  geom_text(aes(x = lon, y = lat, label=" Atlantic House Hotel "), data = data_Hotel1, vjust=1.5,size=3)+ 
  geom_point(aes(x = lon, y = lat), data = data_Hotel2, color = "orange", size = 3) +
  geom_text(aes(x = lon, y = lat, label="Hebasca Hotel"), data = data_Hotel2, vjust=1.5,size=3)


```


##Watercolor map of Bude
```{r, echo = FALSE}
ggmap(watermap) + geom_point(data = df1, aes(x = lon, y = lat), color = 'red') + 
  geom_path(
    aes(x = lon, y = lat), color = "blue", size = 1.5,
    data = path, lineend = "round")+
  geom_point(aes(x = lon, y = lat), data = data_Hotel1, color = "purple", size = 3) +
  geom_text(aes(x = lon, y = lat, label=" Atlantic House Hotel "), data = data_Hotel1, vjust=1.5,size=3)+ 
  geom_point(aes(x = lon, y = lat), data = data_Hotel2, color = "orange", size = 3) +
  geom_text(aes(x = lon, y = lat, label="Hebasca Hotel"), data = data_Hotel2, vjust=1.5,size=3)
```

##Image of Crooklets Beach
```{r, echo= FALSE}

print(crook_beach)
```

##Image of Summerleaze Beach
```{r, echo= FALSE}

print(summ_beach)
```

##Image of Bude North Cornwall Cricket Club
```{r, echo= FALSE}

print(cricket_club)
```

## Image of 2 Hotel Pictures
```{r}
library(magick)
Hotel1 <- image_scale(image_read('https://img.grouponcdn.com/deal/72f1d8b258334b3bb927a00666810983/83/v1/c700x420.jpg'))
print(Hotel1)
Hotel2 <- image_scale(image_read('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVL8ZL69a6IVowFpbURqGbW5DJhpg5yi7tenc5BnDHSqHOLnfY'))
print(Hotel2)

```


